"""
ballistics module:
For reading the JSON files generated by the Aillio Bullet Roaster
"""
__author__ = "themcclure"
__version__ = "1.0a1"

from .utils import get_from_env, Stopwatch, merge_markdown, generate_large_label
from .config import config

from .beans import find_bean_by, Bean, BeanCollection
from .roasts import find_roast_by, Roast, RoastCollection
